logging:
  level:
    web: debug
    org.springframework.data.r2dbc: DEBUG

spring:
  application.name: bootful-web
  #datasource
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/coupons
    username: farmer
    password: q1w2e3..
    initialization-mode: always
    platform: pgsql
  #task
  task.execution.pool:
    max-size: 50
    queue-capacity: 100
    keep-alive: 30S
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  redis:
    host: localhost
  #短信配置
  cloud.alicloud:
    access-key: LTAIrI1OfTFGaA43
    secret-key: CFX0raMd7txvdo7EmqnQpDgZCWFmC5
  #邮件地址配置
  mail:
    host: smtpdm.aliyun.com
    port: 465
    username: admin@support.nerchain.com
    password: lB5GfZZBA8eZSbvG
    test-connection: true
    properties:
      mail.smtp:
        auth: true
        socketFactory.class: javax.net.ssl.SSLSocketFactory
    default-encoding: UTF-8
    protocol: smtp
  #devtools
  devtools:
    add-properties: false
