logging:
  level:
    web: DEBUG
    org.springframework.data.r2dbc: DEBUG
spring:
  application.name: bootiful-web
  r2dbc:
    url: r2dbc:postgres://alexbob.net:5432/coupons
    username: farmer
    password: q1w2e3..
    platform: pgsql
    initialization-mode: always
  rabbitmq:
    host: alexbob.net
    username: coupons
    password: q1w2e3..
  session:
    store-type: redis
  redis:
    host: localhost
    password: 123456

