logging.level.web: debug

spring:
  application:
    name: bootful-taobao
  rabbitmq:
    host: localhost
    username: farmer
    password: q1w2e3..
    template.retry:
      enabled: true
      initial-interval: 2s
  devtools:
    add-properties: false
server:
  port: 8081

# tao bao config
taobao.ke:
  appKey: 25666619
  appSecret: ee6c72c4b1d9bbcdba1f0793887ec8e4
  signMethod: hmac
  apiUrl: https://eco.taobao.com/router/rest
  highKey: 3e01d8ad5e4c46159d85524eae3e7fac
  highUid: 348
  highAPI: http://api.zhetaoke.com:10000/api/

