spring:
  application.name: web-bootful-zuul
  #datasource
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qinke_db?useSSL=NO&serverTimezone=Asia/Shanghai&&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: farmer
    password: q1w2e3..
    initialization-mode: never
  #redis
  redis:
    password: 123456
  devtools:
    add-properties: false
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

mybatis-plus:
  mapper-locations: mybatis-mapper/*.xml
  configuration:
    auto-mapping-unknown-column-behavior: failing
