logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG

spring:
  application.name: qinke-coupons
  #datasource
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qinke_db?useSSL=NO&serverTimezone=Asia/Shanghai&&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: farmer
    password: q1w2e3..
    initialization-mode: always
  #spring session
  session:
    store-type: redis
  #redis
  redis:
    host: localhost

  #jpa
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    open-in-view: false
    show-sql: true
  #task
  task.execution.pool:
    max-size: 50
    queue-capacity: 100
    keep-alive: 30S
  #Thymeleaf
  thymeleaf.cache: false
  #短信配置
  cloud.alicloud:
    access-key: LTAIrI1OfTFGaA43
    secret-key: CFX0raMd7txvdo7EmqnQpDgZCWFmC5
  #邮件地址配置
  mail:
    host: smtpdm.aliyun.com
    port: 465
    username: admin@support.nerchain.com
    password: lB5GfZZBA8eZSbvG
    test-connection: true
    properties:
      mail.smtp:
        auth: true
        socketFactory.class: javax.net.ssl.SSLSocketFactory
    default-encoding: UTF-8
    protocol: smtp
  #oauth2 客户端配置
  security:
    oauth2:
      client:
        registration:
          taobao:
            client-id: 25666619
            client-secret: ee6c72c4b1d9bbcdba1f0793887ec8e4
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: post
            authorization-grant-type: authorization_code
        provider:
          taobao:
            authorization-uri: https://oauth.taobao.com/authorize
            token-uri: https://oauth.taobao.com/token
            user-name-attribute: username
